### ISSUE TITLE
update

### ISSUE THREAD

**Issue by berryma4** [dukescript/dukescript-charts#1]
Is there support for update?
http://www.chartjs.org/docs/#line-chart-prototype-methods

``` java
myLineChart.getData().add(new Values("March",23,24));;

myLineChart.update();

```

**Comment by dukescript** [comment]
Yes, the update of the chart is currently missing. Planned for next version. It should be automatic, e.g.:

``` java
myLineChart.getData().add(new Values("March",23,24));
```

should be enough.

**Comment by dukescript** [comment]
Since c9637c0122b46518807d3b9b7ede83cdca6bc46d some add/remove should be possible following the spirit of chartjs's documentation. Please give it some testing, while verified by unittests, there may be cases that aren't covered.

Refresh after:

``` java
getData().set(...)
```

isn't handled yet.

**Comment by dukescript** [comment]
Everything should be working since a0e6b072918d673a9244f949c9918492b980757d, please give it some testing.
