### ISSUE TITLE
License of teavm.js

### ISSUE THREAD

**Issue by emilianbold** [dukescript/dukescript-charts#2]
I see that https://github.com/dukescript/dukescript-charts/blob/master/charts-api/src/main/java/net/java/html/charts/doc-files/teavm.js has an Oracle CDDL and GPL w/ CPE dual license followed by the MIT license of Knockout.

Which license really applies to that file?

Which license applies to the whole product?

**Comment by dukescript** [comment]
The CDDL license is there, as the file is generated output from the sources in this repository which generally uses NetBeans license (which was CDDL+GPL w/ CPE) - e.g. that's the license of the added work.

The file is generated and includes `knockout.js` file inside which is MIT licensed. The file is included without any modifications - e.g. including its license. As a result it seems the generated file has multiple licenses - which is probably true - as part of it were created from the CDDL sources and and part of it is using MIT library.
